ADPT-118: Rethrow/Remove exceptions in the TaskListener
Taskana/TaskanaAdapter pull request #244
Opened 2020-12-09 08:56 UTC by gitgoodjhe

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

2020-12-09 08:57 UTC, gitgoodjhe commented
https://sonarcloud.io/dashboard?branch=ADPT-118&id=gitgoodjhe_TaskanaAdapter

2021-01-25 14:56 UTC, holgerhagen requested changes
There are still some caught Exceptions in the code. Are they ok?

2021-01-25 14:56 UTC, holgerhagen commented on taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/tasklistener/TaskanaTaskListener.java
> +    } catch (SQLException | JsonProcessingException e) {
Wouldn't it be better to stick to the general Exception in case some runtime Exception or whatever else occur?

2021-03-12 13:08 UTC, holgerhagen approved these changes

2021-03-12 13:17 UTC, merged